# Generated by Django 6.0.5 on 2026-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agentdeal",
            index=models.Index(fields=["agent"], name="agent_deals_agent_i_c813e7_idx"),
        ),
        migrations.AddIndex(
            model_name="agentdeal",
            index=models.Index(fields=["property"], name="agent_deals_propert_9bf116_idx"),
        ),
        migrations.AddIndex(
            model_name="agentdeal",
            index=models.Index(fields=["status"], name="agent_deals_status_09ca1d_idx"),
        ),
    ]
