from django.urls import path

from . import views

app_name = "management"

urlpatterns = [
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("pnl/", views.PnLSummaryView.as_view(), name="pnl"),
    path("brokerage-commissions/stats/", views.BrokerageCommissionStatsView.as_view(), name="brokerage-commission-stats"),
    path("users/", views.ManagementUserListView.as_view(), name="user-list"),
    path("users/invite/", views.ManagementUserInviteView.as_view(), name="user-invite"),
    path("users/<int:pk>/", views.ManagementUserDetailUpdateView.as_view(), name="user-detail"),
    path("properties/", views.ManagementPropertyListView.as_view(), name="property-list"),
    path("properties/map/", views.ManagementPropertyMapView.as_view(), name="property-map"),
    path("properties/import/", views.ManagementPropertyImportView.as_view(), name="property-import"),
    path("one-off-deals/", views.OneOffDealListCreateView.as_view(), name="one-off-deal-list-create"),
    path("one-off-deals/<int:pk>/", views.OneOffDealDetailView.as_view(), name="one-off-deal-detail"),
    path("one-off-deals/<int:pk>/activate/", views.OneOffDealActivateView.as_view(), name="one-off-deal-activate"),
    path("one-off-deals/<int:pk>/pause/", views.OneOffDealPauseView.as_view(), name="one-off-deal-pause"),
    path("one-off-deals/<int:pk>/close-won/", views.OneOffDealCloseWonView.as_view(), name="one-off-deal-close-won"),
    path("one-off-deals/<int:pk>/close-lost/", views.OneOffDealCloseLostView.as_view(), name="one-off-deal-close-lost"),
    path("one-off-deals/<int:pk>/archive/", views.OneOffDealArchiveView.as_view(), name="one-off-deal-archive"),
    path("one-off-deals/<int:pk>/receipt/", views.OneOffCommissionReceiptView.as_view(), name="one-off-receipt"),
    path(
        "one-off-deals/<int:pk>/receipt/attachments/",
        views.OneOffCommissionReceiptAttachmentView.as_view(),
        name="one-off-receipt-attachments",
    ),
    path("assignees/", views.ManagementAssigneeListView.as_view(), name="assignee-list"),
    path("leases/", views.LeaseListView.as_view(), name="lease-list"),
    path("owner-agreements/", views.OwnerAgreementListView.as_view(), name="owner-agreement-list"),
    path("payments/", views.PaymentListView.as_view(), name="payment-list"),
    path("payments/stats/", views.PaymentStatsView.as_view(), name="payment-stats"),
    path("payouts/", views.PayoutListView.as_view(), name="payout-list"),
    path("payouts/stats/", views.PayoutStatsView.as_view(), name="payout-stats"),
    path("settlements/", views.SettlementListView.as_view(), name="settlement-list"),
    path("service-requests/", views.ManagementServiceRequestListView.as_view(), name="service-request-list"),
    path("service-requests/stats/", views.ManagementServiceRequestStatsView.as_view(), name="service-request-stats"),
    path(
        "service-requests/<int:pk>/cancel/",
        views.ManagementServiceRequestCancelView.as_view(),
        name="service-request-cancel",
    ),
    path(
        "service-requests/<int:pk>/comments/",
        views.ManagementServiceRequestCommentsView.as_view(),
        name="service-request-comments",
    ),
    path(
        "service-requests/<int:pk>/photos/",
        views.ManagementServiceRequestPhotosView.as_view(),
        name="service-request-photos",
    ),
    path("queue-counts/", views.ManagementQueueCountsView.as_view(), name="queue-counts"),
    path("onboardings/", views.ManagementOnboardingListView.as_view(), name="onboarding-list"),
    path("onboardings/stats/", views.ManagementOnboardingStatsView.as_view(), name="onboarding-stats"),
    path("onboardings/<int:pk>/", views.ManagementOnboardingDetailView.as_view(), name="onboarding-detail"),
    path("onboardings/<int:pk>/approve/", views.ManagementOnboardingApproveView.as_view(), name="onboarding-approve"),
    path("onboardings/<int:pk>/reject/", views.ManagementOnboardingRejectView.as_view(), name="onboarding-reject"),
    path(
        "onboardings/<int:pk>/request-info/",
        views.ManagementOnboardingRequestInfoView.as_view(),
        name="onboarding-request-info",
    ),
    path("bookings/", views.ManagementBookingListView.as_view(), name="booking-list"),
    path("bookings/<int:pk>/approve/", views.ManagementBookingApproveView.as_view(), name="booking-approve"),
    path("bookings/<int:pk>/reject/", views.ManagementBookingRejectView.as_view(), name="booking-reject"),
    path("bookings/<int:pk>/convert/", views.ManagementBookingConvertView.as_view(), name="booking-convert"),
    path("leads/", views.ManagementLeadListView.as_view(), name="lead-list"),
    path("leads/stats/", views.ManagementLeadStatsView.as_view(), name="lead-stats"),
    path("inquiries/", views.ManagementInquiryListView.as_view(), name="inquiry-list"),
    path("inquiries/<int:pk>/", views.ManagementInquiryStatusView.as_view(), name="inquiry-status"),
    path("viewing-requests/", views.ManagementViewingRequestListView.as_view(), name="viewing-request-list"),
    path(
        "viewing-requests/<int:pk>/confirm/",
        views.ManagementViewingRequestConfirmView.as_view(),
        name="viewing-request-confirm",
    ),
    path(
        "viewing-requests/<int:pk>/cancel/",
        views.ManagementViewingRequestCancelView.as_view(),
        name="viewing-request-cancel",
    ),
    path(
        "viewing-requests/<int:pk>/propose-time/",
        views.ManagementViewingRequestProposeTimeView.as_view(),
        name="viewing-request-propose-time",
    ),
    path("vas-orders/", views.ManagementVASOrderListView.as_view(), name="vas-order-list"),
    path("vas-orders/stats/", views.ManagementVASStatsView.as_view(), name="vas-order-stats"),
    path("vas-orders/<int:pk>/", views.ManagementVASOrderDetailView.as_view(), name="vas-order-detail"),
    path("vas-orders/<int:pk>/status/", views.ManagementVASOrderStatusView.as_view(), name="vas-order-status"),
    path("vas-partners/", views.ManagementVASPartnersView.as_view(), name="vas-partners"),
    path("vacancy/", views.ManagementVacancyView.as_view(), name="vacancy"),
]
