# Generated by Django 6.0.5 on 2026-06-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contract", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "currency",
                    models.CharField(choices=core.constants.Currency.choices, max_length=3, verbose_name="Currency"),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=15, verbose_name="Rate")),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "exchange_rates",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount")),
                (
                    "currency",
                    models.CharField(
                        choices=core.constants.Currency.choices, default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.PaymentStatus.choices,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=core.constants.PaymentMethod.choices,
                        default="cash",
                        max_length=20,
                        verbose_name="Method",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="contract.lease"
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Paid By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(fields=["lease"], name="payments_lease_i_bbeb30_idx"),
                    models.Index(fields=["tenant"], name="payments_tenant__d18216_idx"),
                    models.Index(fields=["status"], name="payments_status_d621e5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayoutSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount")),
                (
                    "currency",
                    models.CharField(
                        choices=core.constants.Currency.choices, default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Scheduled Date")),
                ("paid_date", models.DateField(blank=True, null=True, verbose_name="Paid Date")),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.PayoutStatus.choices,
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "owner_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_schedules",
                        to="contract.owneragreement",
                        verbose_name="Owner Agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payout Schedule",
                "verbose_name_plural": "Payout Schedules",
                "db_table": "payout_schedules",
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(fields=["owner"], name="payout_sche_owner_i_9adddb_idx"),
                    models.Index(fields=["status"], name="payout_sche_status_ebc505_idx"),
                ],
            },
        ),
    ]
