# Generated by Django 6.0.5 on 2026-06-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_ref",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Gateway Reference"),
        ),
        migrations.AddField(
            model_name="payoutschedule",
            name="source_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_payout",
                to="finance.payment",
                verbose_name="Source Payment",
            ),
        ),
    ]
