# Generated by Django 6.0.5 on 2026-07-06 18:22

from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_payment_gateway_ref_payoutschedule_source_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutschedule",
            name="method",
            field=models.CharField(
                choices=core.constants.PayoutMethod.choices,
                default="bank_transfer",
                max_length=20,
                verbose_name="Method",
            ),
        ),
        migrations.AddField(
            model_name="payoutschedule",
            name="status_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Status Reason"),
        ),
    ]
