# Generated by Django 6.0.5 on 2026-07-23 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_remove_owneragreement_owner_guaranteed_amount_and_more"),
        ("finance", "0003_payoutschedule_method_payoutschedule_status_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutschedule",
            name="source_payment",
        ),
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(choices=core.constants.PaymentKind.choices, default="rent", max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="rental_period",
            field=models.DateField(blank=True, null=True, verbose_name="Rental Period"),
        ),
        migrations.AddField(
            model_name="payoutschedule",
            name="kind",
            field=models.CharField(choices=core.constants.PayoutKind.choices, default="base", max_length=30),
        ),
        migrations.CreateModel(
            name="OwnerSettlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("covered_days", models.PositiveSmallIntegerField()),
                ("days_in_month", models.PositiveSmallIntegerField()),
                ("gross_floor_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("commission_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("currency", models.CharField(choices=core.constants.Currency.choices, max_length=3)),
                ("rent_received_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("settlement_base_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("commission_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("owner_payout_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("ideal_cash_exposure", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="contract.owneragreement",
                    ),
                ),
            ],
            options={
                "db_table": "owner_settlements",
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddField(
            model_name="payoutschedule",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="finance.ownersettlement",
                verbose_name="Settlement",
            ),
        ),
        migrations.CreateModel(
            name="RentReceiptAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_allocations",
                        to="finance.payment",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_allocations",
                        to="finance.ownersettlement",
                    ),
                ),
            ],
            options={
                "db_table": "rent_receipt_allocations",
            },
        ),
        migrations.AddIndex(
            model_name="ownersettlement",
            index=models.Index(fields=["owner", "period_start"], name="owner_settl_owner_i_6f41b8_idx"),
        ),
        migrations.AddConstraint(
            model_name="ownersettlement",
            constraint=models.UniqueConstraint(
                fields=("owner_agreement", "period_start"), name="unique_agreement_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentreceiptallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "settlement"), name="unique_payment_settlement_allocation"
            ),
        ),
    ]
