# Generated by Django 6.0.5 on 2026-06-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(choices=core.constants.LeaseStatus.choices, default="active", max_length=20),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="property.property"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="leases", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease",
                "verbose_name_plural": "Leases",
                "db_table": "leases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaseRenewal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("renewal_date", models.DateField()),
                ("new_start_date", models.DateField()),
                ("new_end_date", models.DateField()),
                ("new_monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "new_lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="renewals_as_new", to="contract.lease"
                    ),
                ),
                (
                    "previous_lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renewals_as_previous",
                        to="contract.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Renewal",
                "verbose_name_plural": "Lease Renewals",
                "db_table": "lease_renewals",
                "ordering": ["-renewal_date"],
            },
        ),
        migrations.CreateModel(
            name="OwnerAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("agreement_number", models.CharField(max_length=50, unique=True)),
                ("signed_date", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.OwnerAgreementStatus.choices, default="active", max_length=20
                    ),
                ),
                ("terms", models.TextField(blank=True, null=True)),
                ("commission_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_agreements",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner Agreement",
                "verbose_name_plural": "Owner Agreements",
                "db_table": "owner_agreements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="owner_agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="contract.owneragreement"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["property"], name="leases_propert_07dfa4_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["tenant"], name="leases_tenant__c311df_idx"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["status"], name="leases_status_3db7e6_idx"),
        ),
    ]
