# Generated by Django 6.0.5 on 2026-06-15 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leaserenewal",
            index=models.Index(fields=["previous_lease"], name="lease_renew_previou_092051_idx"),
        ),
        migrations.AddIndex(
            model_name="leaserenewal",
            index=models.Index(fields=["new_lease"], name="lease_renew_new_lea_913456_idx"),
        ),
        migrations.AddIndex(
            model_name="owneragreement",
            index=models.Index(fields=["owner"], name="owner_agree_owner_i_5a4a43_idx"),
        ),
        migrations.AddIndex(
            model_name="owneragreement",
            index=models.Index(fields=["property"], name="owner_agree_propert_af61e0_idx"),
        ),
        migrations.AddIndex(
            model_name="owneragreement",
            index=models.Index(fields=["status"], name="owner_agree_status_d3a79b_idx"),
        ),
    ]
