# Generated by Django 6.0.5 on 2026-06-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0002_leaserenewal_lease_renew_previou_092051_idx_and_more"),
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("version", models.CharField(max_length=20, unique=True, verbose_name="Version")),
                ("body", models.TextField(verbose_name="Body")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
            ],
            options={
                "verbose_name": "Public Offer",
                "verbose_name_plural": "Public Offers",
                "db_table": "public_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerOnboarding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.OnboardingStatus.choices,
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("offer_version", models.CharField(blank=True, max_length=20, null=True, verbose_name="Offer Version")),
                ("offer_terms_snapshot", models.TextField(blank=True, null=True, verbose_name="Offer Terms Snapshot")),
                ("offer_accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="Offer Accepted At")),
                ("review_notes", models.TextField(blank=True, null=True, verbose_name="Review Notes")),
                (
                    "generated_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboardings",
                        to="contract.owneragreement",
                        verbose_name="Generated Agreement",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboardings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboardings",
                        to="property.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_onboardings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner Onboarding",
                "verbose_name_plural": "Owner Onboardings",
                "db_table": "owner_onboardings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner"], name="owner_onboa_owner_i_85ae21_idx"),
                    models.Index(fields=["property"], name="owner_onboa_propert_ce188b_idx"),
                    models.Index(fields=["status"], name="owner_onboa_status_e80546_idx"),
                ],
            },
        ),
    ]
