# Generated by Django 6.0.5 on 2026-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_publicoffer_owneronboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="owneragreement",
            name="owner_guaranteed_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="owneragreement",
            name="tenant_charge_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
