# Generated by Django 6.0.5 on 2026-07-23 07:20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0005_backfill_agreement_amounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owneragreement",
            name="owner_guaranteed_amount",
        ),
        migrations.RemoveField(
            model_name="owneragreement",
            name="tenant_charge_amount",
        ),
        migrations.AddField(
            model_name="owneragreement",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="owneragreement",
            name="gross_floor_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="owneragreement",
            name="payout_day",
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
