# Generated by Django 6.0.5 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0007_owneragreement_previous_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owneragreement",
            name="accepted_locale",
            field=models.CharField(blank=True, default="en", max_length=10, verbose_name="Accepted Locale"),
        ),
        migrations.AddField(
            model_name="owneronboarding",
            name="offer_accepted_locale",
            field=models.CharField(blank=True, default="en", max_length=10, verbose_name="Offer Accepted Locale"),
        ),
        migrations.AddField(
            model_name="publicoffer",
            name="body_en",
            field=models.TextField(null=True, verbose_name="Body"),
        ),
        migrations.AddField(
            model_name="publicoffer",
            name="body_ru",
            field=models.TextField(null=True, verbose_name="Body"),
        ),
        migrations.AddField(
            model_name="publicoffer",
            name="body_uz",
            field=models.TextField(null=True, verbose_name="Body"),
        ),
    ]
