# Generated by Django 6.0.5 on 2026-06-07 15:38

import account.managers
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("patronymic", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(choices=core.constants.UserRole.choices, default="mgmt", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                ("telegram_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", account.managers.UserManager()),
            ],
        ),
    ]
