# Generated by Django 6.0.5 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_tokenblacklist_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/avatars/"),
        ),
    ]
