# Generated by Django 6.0.5 on 2026-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="Email Address")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("spam", "Spam"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address")),
                ("user_agent", models.CharField(blank=True, max_length=512, verbose_name="User Agent")),
                ("admin_notes", models.TextField(blank=True, verbose_name="Staff Notes")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
            ],
            options={
                "verbose_name": "Support Inquiry",
                "verbose_name_plural": "Support Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
