# Generated by Django 6.0.5 on 2026-08-09 15:37

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0006_listing_minimum_stay_listing_price_includes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("user_archived_at", models.DateTimeField(blank=True, null=True, verbose_name="User Archived At")),
                (
                    "user_deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="User Deleted At"),
                ),
                ("user_muted", models.BooleanField(default=False, verbose_name="User Muted")),
                (
                    "user_last_read_message_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="User Last Read Message ID"),
                ),
                ("user_unread_count", models.PositiveIntegerField(default=0, verbose_name="User Unread Count")),
                ("staff_archived_at", models.DateTimeField(blank=True, null=True, verbose_name="Staff Archived At")),
                (
                    "staff_last_read_message_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Staff Last Read Message ID"),
                ),
                ("staff_unread_count", models.PositiveIntegerField(default=0, verbose_name="Staff Unread Count")),
                ("is_user_blocked", models.BooleanField(db_index=True, default=False, verbose_name="Is User Blocked")),
                ("blocked_at", models.DateTimeField(blank=True, null=True, verbose_name="Blocked At")),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Last Message At"),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked By",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="marketplace.listing",
                        verbose_name="Listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "chat_conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "sender_side",
                    models.CharField(
                        choices=core.constants.ChatSenderSide.choices, max_length=10, verbose_name="Sender Side"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=core.constants.ChatMessageKind.choices,
                        default="text",
                        max_length=10,
                        verbose_name="Kind",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=1024, null=True, verbose_name="Text")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        height_field="image_height",
                        null=True,
                        upload_to=chat.models.chat_image_upload_to,
                        verbose_name="Image",
                        width_field="image_width",
                    ),
                ),
                ("image_width", models.PositiveIntegerField(blank=True, null=True, verbose_name="Image Width")),
                ("image_height", models.PositiveIntegerField(blank=True, null=True, verbose_name="Image Height")),
                (
                    "image_size_bytes",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Image Size Bytes"),
                ),
                ("client_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="Client ID")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Read At")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="Conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "chat_messages",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
                verbose_name="Last Message",
            ),
        ),
        migrations.CreateModel(
            name="ConversationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "reason",
                    models.CharField(
                        choices=core.constants.ChatReportReason.choices, max_length=20, verbose_name="Reason"
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500, verbose_name="Note")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="chat.conversation",
                        verbose_name="Conversation",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Report",
                "verbose_name_plural": "Conversation Reports",
                "db_table": "chat_conversation_reports",
                "indexes": [
                    models.Index(fields=["conversation"], name="chat_conver_convers_0b3612_idx"),
                    models.Index(fields=["resolved_at"], name="chat_conver_resolve_19b427_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "id"], name="chat_messag_convers_9e0e50_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "-id"], name="chat_messag_convers_9cdf7a_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "read_at"], name="chat_messag_convers_5cba9b_idx"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("conversation", "client_id"),
                name="uniq_chat_message_client_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "text"), ("text__isnull", False)),
                    models.Q(("kind", "image"), ("image__isnull", False), models.Q(("image", ""), _negated=True)),
                    _connector="OR",
                ),
                name="chat_message_payload_matches_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["listing"], name="chat_conver_listing_ebea4a_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["user"], name="chat_conver_user_id_c6ec36_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["-last_message_at"], name="chat_conver_last_me_2102b2_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["updated_at"], name="chat_conver_updated_b5a0fe_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["user", "user_deleted_at"], name="chat_conver_user_id_c25098_idx"),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("listing", "user"),
                name="uniq_conversation_per_listing_user",
            ),
        ),
    ]
