# Generated by Django 6.0.5 on 2026-08-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="staff_realtime_version",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Staff Realtime Version"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user_realtime_version",
            field=models.PositiveBigIntegerField(default=0, verbose_name="User Realtime Version"),
        ),
        migrations.CreateModel(
            name="ChatRealtimeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("audience", models.CharField(max_length=10, verbose_name="Audience")),
                ("conversation_id", models.BigIntegerField(db_index=True, verbose_name="Conversation ID")),
                ("conversation_version", models.PositiveBigIntegerField(verbose_name="Conversation Version")),
                ("event_type", models.CharField(max_length=64, verbose_name="Event Type")),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Realtime Event",
                "verbose_name_plural": "Chat Realtime Events",
                "db_table": "chat_realtime_events",
                "indexes": [
                    models.Index(fields=["audience", "recipient_user", "id"], name="chat_realti_audienc_584dfa_idx"),
                    models.Index(fields=["created_at"], name="chat_realti_created_340072_idx"),
                ],
            },
        ),
    ]
