# Generated by Django 6.0.5 on 2026-06-07 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("city", models.CharField(default="Toshkent", max_length=100)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "districts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("rooms", models.PositiveSmallIntegerField()),
                ("area_sqm", models.PositiveSmallIntegerField()),
                ("floor", models.PositiveSmallIntegerField()),
                ("total_floors", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(choices=core.constants.PropertyStatus.choices, default="vacant", max_length=20),
                ),
                ("score", models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ("map_lat", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("map_lon", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "tariff",
                    models.CharField(choices=core.constants.TariffChoices.choices, default="standard", max_length=20),
                ),
                ("ask_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ask_currency", models.CharField(default="USD", max_length=3)),
                ("owner_guaranteed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("owner_guaranteed_currency", models.CharField(default="USD", max_length=3)),
                ("tenant_charge_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tenant_charge_currency", models.CharField(default="USD", max_length=3)),
                ("vacant_since", models.DateField(blank=True, null=True)),
                ("vacant_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="properties", to="property.district"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("image", models.ImageField(upload_to="properties/photos/")),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="property.property"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Photo",
                "verbose_name_plural": "Property Photos",
                "db_table": "property_photos",
                "ordering": ["sort_order", "-is_primary"],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["district"], name="properties_distric_49eaea_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["owner"], name="properties_owner_i_921947_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="properties_status_e6008a_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["map_lat", "map_lon"], name="properties_map_lat_6ee7c6_idx"),
        ),
    ]
