# Generated by Django 6.0.5 on 2026-06-25 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "db_table": "amenities",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="deposit_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="deposit_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="property",
            name="furnishing",
            field=models.CharField(choices=core.constants.FurnishingType.choices, default="unfurnished", max_length=20),
        ),
        migrations.AddField(
            model_name="property",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(choices=core.constants.PropertyType.choices, default="apartment", max_length=20),
        ),
        migrations.AddField(
            model_name="property",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.ManyToManyField(blank=True, related_name="properties", to="property.amenity"),
        ),
    ]
