# Generated by Django 6.0.5 on 2026-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_seed_amenities_backfill_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyphoto",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Caption"),
        ),
    ]
