# Generated by Django 6.0.5 on 2026-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_propertyphoto_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="review_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Review count"),
        ),
    ]
