# Generated by Django 6.0.5 on 2026-07-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0007_alter_property_address_alter_property_area_sqm_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneOffCommissionReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(choices=core.constants.Currency.choices, max_length=3)),
                ("received_date", models.DateField()),
                ("method", models.CharField(choices=core.constants.PaymentMethod.choices, max_length=20)),
                ("reference", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "verbose_name": "One-off commission receipt",
                "verbose_name_plural": "One-off commission receipts",
                "db_table": "one_off_commission_receipts",
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OneOffDeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("seller_name", models.CharField(max_length=150)),
                ("seller_phone", models.CharField(max_length=30)),
                ("seller_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("renter_name", models.CharField(blank=True, max_length=150, null=True)),
                ("renter_phone", models.CharField(blank=True, max_length=30, null=True)),
                ("renter_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("channel", models.CharField(choices=core.constants.OneOffChannel.choices, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.OneOffDealStatus.choices, db_index=True, default="draft", max_length=20
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=core.constants.BrokerageCommissionType.choices, default="none", max_length=20
                    ),
                ),
                (
                    "commission_fixed_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("commission_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "commission_currency",
                    models.CharField(choices=core.constants.Currency.choices, default="USD", max_length=3),
                ),
                ("agreed_monthly_rent", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "agreed_currency",
                    models.CharField(choices=core.constants.Currency.choices, default="USD", max_length=3),
                ),
                ("close_date", models.DateField(blank=True, null=True)),
                ("close_notes", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("commission_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("commission_uzs_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                (
                    "commission_conversion_rate",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
            ],
            options={
                "verbose_name": "One-off brokerage deal",
                "verbose_name_plural": "One-off brokerage deals",
                "db_table": "one_off_deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="engagement_type",
            field=models.CharField(
                choices=core.constants.PropertyEngagementType.choices, db_index=True, default="managed", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["engagement_type", "status"], name="properties_engagem_5e9f4f_idx"),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("engagement_type", "managed"), ("owner__isnull", True), _connector="OR"),
                name="one_off_property_has_no_owner",
            ),
        ),
        migrations.AddField(
            model_name="oneoffcommissionreceipt",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_one_off_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="oneoffdeal",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_one_off_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="oneoffdeal",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="one_off_deal", to="property.property"
            ),
        ),
        migrations.AddField(
            model_name="oneoffcommissionreceipt",
            name="deal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="receipt", to="property.oneoffdeal"
            ),
        ),
        migrations.AddIndex(
            model_name="oneoffdeal",
            index=models.Index(fields=["status"], name="one_off_dea_status_dd8c3d_idx"),
        ),
        migrations.AddIndex(
            model_name="oneoffdeal",
            index=models.Index(fields=["channel", "status"], name="one_off_dea_channel_349c58_idx"),
        ),
    ]
