# Generated by Django 6.0.5 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("property", "0008_oneoffcommissionreceipt_oneoffdeal_and_more")]

    operations = [
        migrations.CreateModel(
            name="OneOffCommissionReceiptAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("file", models.FileField(upload_to="one_off_brokerage/receipts/")),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=100)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="property.oneoffcommissionreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "One-off commission receipt attachment",
                "verbose_name_plural": "One-off commission receipt attachments",
                "db_table": "one_off_commission_receipt_attachments",
                "ordering": ["created_at"],
            },
        )
    ]
