# Generated by Django 6.0.5 on 2026-07-19 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_oneoffcommissionreceiptattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="bathrooms",
        ),
    ]
