# Generated by Django 6.0.5 on 2026-08-25 15:05

from django.conf import settings
from django.db import migrations, models

import core.constants


def prune_draft_properties_and_backfill(apps, schema_editor):
    Property = apps.get_model("property", "Property")
    PropertyPhoto = apps.get_model("property", "PropertyPhoto")
    VerificationVisit = apps.get_model("property", "VerificationVisit")
    OneOffDeal = apps.get_model("property", "OneOffDeal")

    db_alias = schema_editor.connection.alias
    draft_properties = Property.objects.using(db_alias).filter(status="draft")
    for prop in draft_properties:
        PropertyPhoto.objects.using(db_alias).filter(property=prop).delete()
        VerificationVisit.objects.using(db_alias).filter(property=prop).delete()
        OneOffDeal.objects.using(db_alias).filter(property=prop).delete()
        prop.delete()

    OneOffDeal.objects.using(db_alias).filter(status="draft").delete()

    Property.objects.using(db_alias).filter(tariff__isnull=True).update(tariff="standard")
    Property.objects.using(db_alias).filter(tariff="").update(tariff="standard")

    if Property.objects.using(db_alias).filter(status="draft").exists():
        raise RuntimeError("Migration failed: draft properties still exist.")
    if OneOffDeal.objects.using(db_alias).filter(status="draft").exists():
        raise RuntimeError("Migration failed: draft one-off deals still exist.")


def _choose_primary_photo_ids(photo_rows):
    fallback_by_property = {}
    primary_by_property = {}

    for property_id, photo_id, is_primary in photo_rows:
        fallback_by_property.setdefault(property_id, photo_id)
        if is_primary:
            primary_by_property.setdefault(property_id, photo_id)

    return [
        primary_by_property.get(property_id, fallback_photo_id)
        for property_id, fallback_photo_id in fallback_by_property.items()
    ]


def normalize_property_photo_primaries(apps, schema_editor):
    PropertyPhoto = apps.get_model("property", "PropertyPhoto")
    db_alias = schema_editor.connection.alias
    photos = PropertyPhoto.objects.using(db_alias).all()
    photo_rows = photos.order_by("property_id", "id").values_list("property_id", "id", "is_primary").iterator()
    primary_photo_ids = _choose_primary_photo_ids(photo_rows)

    photos.update(is_primary=False)
    if primary_photo_ids:
        photos.filter(pk__in=primary_photo_ids).update(is_primary=True)


TRIGGER_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = 'check_listing_photos_count'
    ) THEN
        DROP TRIGGER IF EXISTS trg_check_listing_photos_count ON property_photos;
        DROP FUNCTION check_listing_photos_count();
    END IF;
END $$;

CREATE OR REPLACE FUNCTION check_listing_photos_count()
RETURNS TRIGGER AS $$
DECLARE
    prop_id INT;
    listing_st VARCHAR;
    photo_cnt INT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        prop_id := OLD.property_id;
    ELSE
        prop_id := NEW.property_id;
    END IF;

    SELECT l.status INTO listing_st
    FROM properties p
    JOIN listings l ON l.property_id = p.id AND l.deleted_at IS NULL
    WHERE p.id = prop_id AND p.deleted_at IS NULL;

    IF listing_st IN ('published', 'pending_review') THEN
        SELECT COUNT(*) INTO photo_cnt
        FROM property_photos
        WHERE property_id = prop_id;

        IF photo_cnt < 5 OR photo_cnt > 12 THEN
            RAISE EXCEPTION 'Marketplace listings must have between 5 and 12 photos, found % for property %', photo_cnt, prop_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_listing_photos_count ON property_photos;
CREATE CONSTRAINT TRIGGER trg_check_listing_photos_count
AFTER INSERT OR UPDATE OR DELETE ON property_photos
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION check_listing_photos_count();
"""

DROP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS trg_check_listing_photos_count ON property_photos;
DROP FUNCTION IF EXISTS check_listing_photos_count();
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("property", "0012_propertyphoto_preview_image_propertyphoto_display_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(prune_draft_properties_and_backfill, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="oneoffdeal",
            name="status",
            field=models.CharField(
                choices=core.constants.OneOffDealStatus.choices, db_index=True, default="active", max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="oneoffdeal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("commission_type", "none"),
                        ("commission_fixed_amount__isnull", True),
                        ("commission_percentage__isnull", True),
                    ),
                    models.Q(
                        ("commission_type", "fixed"),
                        ("commission_fixed_amount__gt", 0),
                        ("commission_percentage__isnull", True),
                    ),
                    models.Q(
                        ("commission_type", "percentage"),
                        ("commission_percentage__gt", 0),
                        ("commission_percentage__lte", 100),
                        ("commission_fixed_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="one_off_deal_commission_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("rooms__isnull", True), ("rooms__gt", 0), _connector="OR"),
                name="property_rooms_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_sqm__isnull", True), ("area_sqm__gt", 0), _connector="OR"),
                name="property_area_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("ask_price__isnull", True), ("ask_price__gte", 0), _connector="OR"),
                name="property_ask_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__isnull", True), ("deposit_amount__gte", 0), _connector="OR"),
                name="property_deposit_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("owner_guaranteed_price__isnull", True), ("owner_guaranteed_price__gte", 0), _connector="OR"
                ),
                name="property_owner_guaranteed_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenant_charge_price__isnull", True), ("tenant_charge_price__gte", 0), _connector="OR"
                ),
                name="property_tenant_charge_price_nonnegative",
            ),
        ),
        migrations.RunPython(normalize_property_photo_primaries, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="propertyphoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)), fields=("property",), name="unique_primary_photo_per_property"
            ),
        ),
        migrations.RunSQL(TRIGGER_SQL, reverse_sql=DROP_TRIGGER_SQL),
    ]
