# Generated by Django 6.0.5 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0013_alter_oneoffdeal_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="amenity",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="city_en",
            field=models.CharField(default="Toshkent", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="city_ru",
            field=models.CharField(default="Toshkent", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="city_uz",
            field=models.CharField(default="Toshkent", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="district",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="district",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="property",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="caption_en",
            field=models.CharField(blank=True, default="", max_length=120, null=True, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="caption_ru",
            field=models.CharField(blank=True, default="", max_length=120, null=True, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="caption_uz",
            field=models.CharField(blank=True, default="", max_length=120, null=True, verbose_name="Caption"),
        ),
    ]
