# Generated by Django 6.0.5 on 2026-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0015_backfill_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="landmark",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
