# Generated by Django 6.0.5 on 2026-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0016_property_landmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="landmark_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="landmark_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="landmark_uz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
