# Generated by Django 6.0.5 on 2026-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileHomeBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("title_en", models.CharField(max_length=200, null=True, verbose_name="Title")),
                ("title_uz", models.CharField(max_length=200, null=True, verbose_name="Title")),
                ("title_ru", models.CharField(max_length=200, null=True, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("description_en", models.TextField(null=True, verbose_name="Description")),
                ("description_uz", models.TextField(null=True, verbose_name="Description")),
                ("description_ru", models.TextField(null=True, verbose_name="Description")),
                ("tag", models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Tag")),
                ("tag_en", models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Tag")),
                ("tag_uz", models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Tag")),
                ("tag_ru", models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Tag")),
                ("icon", models.CharField(default="circle_check", max_length=50, verbose_name="Icon Name")),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name="Sort Order")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is Active")),
            ],
            options={
                "verbose_name": "Mobile Home Banner",
                "verbose_name_plural": "Mobile Home Banners",
                "db_table": "mobile_home_banners",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
