# Generated by Django 6.0.5 on 2026-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_leaserenewal_lease_renew_previou_092051_idx_and_more"),
        ("marketplace", "0001_initial"),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["is_active"], name="listings_is_acti_fd46bf_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["is_featured"], name="listings_is_feat_01aa9f_idx"),
        ),
        migrations.AddIndex(
            model_name="viewingrequest",
            index=models.Index(fields=["listing"], name="viewing_req_listing_139c85_idx"),
        ),
        migrations.AddIndex(
            model_name="viewingrequest",
            index=models.Index(fields=["status"], name="viewing_req_status_f29dc6_idx"),
        ),
    ]
