# Generated by Django 6.0.5 on 2026-06-19 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_publicoffer_owneronboarding"),
        ("marketplace", "0002_listing_listings_is_acti_fd46bf_idx_and_more"),
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("requested_start_date", models.DateField(verbose_name="Requested Start Date")),
                ("requested_end_date", models.DateField(verbose_name="Requested End Date")),
                (
                    "monthly_rent_offer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Monthly Rent Offer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.BookingStatus.choices,
                        default="requested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True, verbose_name="Message")),
                (
                    "converted_lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_bookings",
                        to="contract.lease",
                        verbose_name="Converted Lease",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="marketplace.listing",
                        verbose_name="Listing",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="property.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["listing"], name="bookings_listing_f5464a_idx"),
                    models.Index(fields=["tenant"], name="bookings_tenant__51b695_idx"),
                    models.Index(fields=["status"], name="bookings_status_51373b_idx"),
                ],
            },
        ),
    ]
