# Generated by Django 6.0.5 on 2026-06-25 19:26

import django.db.models.deletion
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_publicoffer_owneronboarding"),
        ("marketplace", "0003_booking"),
        ("property", "0002_amenity_property_bathrooms_property_deposit_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(choices=core.constants.ContactInquiryStatus.choices, default="new", max_length=20),
                ),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "db_table": "contact_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ Item",
                "verbose_name_plural": "FAQ Items",
                "db_table": "faq_items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="listing",
            name="deposit_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="monthly_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(choices=core.constants.ListingStatus.choices, default="published", max_length=20),
        ),
        migrations.AddField(
            model_name="listing",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viewingrequest",
            name="preferred_time",
            field=models.CharField(
                blank=True, choices=core.constants.ViewingTimeSlot.choices, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="viewingrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="listings_status_c3eaec_idx"),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquiries",
                to="marketplace.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="contactinquiry",
            index=models.Index(fields=["status"], name="contact_inq_status_b7ab91_idx"),
        ),
    ]
