# Generated by Django 6.0.5 on 2026-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_backfill_listing_status_seed_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="minimum_stay",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "1 month"), (3, "3 months"), (6, "6 months"), (12, "12 months")], null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="price_includes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
