# Generated by Django 6.0.5 on 2026-08-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_recentsearchactivity_listingviewactivity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="listingviewactivity",
            new_name="listing_vie_user_id_630077_idx",
            old_name="listing_view_user_id_44f1c7_idx",
        ),
        migrations.RenameIndex(
            model_name="listingviewactivity",
            new_name="listing_vie_listing_1660f9_idx",
            old_name="listing_view_listing_76a3e5_idx",
        ),
        migrations.RenameIndex(
            model_name="recentsearchactivity",
            new_name="recent_sear_user_id_a4e6a5_idx",
            old_name="recent_sear_user_id_0f249d_idx",
        ),
    ]
