# Generated by Django 6.0.5 on 2026-08-25 15:05

from decimal import Decimal

from django.db import migrations, models


def backfill_legacy_listings_and_verify_no_drafts(apps, schema_editor):
    Listing = apps.get_model("marketplace", "Listing")
    Property = apps.get_model("property", "Property")

    Listing.objects.filter(status="draft").delete()

    for listing in Listing.objects.filter(models.Q(deposit_amount__isnull=True) | models.Q(minimum_stay__isnull=True)):
        if listing.deposit_amount is None:
            prop = Property.objects.filter(id=listing.property_id).first()
            listing.deposit_amount = (
                prop.deposit_amount if prop and prop.deposit_amount is not None else Decimal("0.00")
            )
        if listing.minimum_stay is None:
            listing.minimum_stay = 6
        listing.save(update_fields=["deposit_amount", "minimum_stay"])

    if Listing.objects.filter(status="draft").exists():
        raise RuntimeError("Migration failed: draft listings still exist.")


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0007_owneragreement_previous_agreement_and_more"),
        ("marketplace", "0010_rename_listing_view_user_id_44f1c7_idx_listing_vie_user_id_630077_idx_and_more"),
        ("property", "0013_alter_oneoffdeal_status_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_listings_and_verify_no_drafts, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_price__isnull", True), ("monthly_price__gte", 0), _connector="OR"),
                name="listing_monthly_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__isnull", True), ("deposit_amount__gte", 0), _connector="OR"),
                name="listing_deposit_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_active", False)) | models.Q(("status", "published")),
                name="listing_is_active_parity",
            ),
        ),
    ]
