# Generated by Django 6.0.5 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0011_listing_listing_monthly_price_nonnegative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqitem",
            name="answer_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="answer_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="answer_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
