# Generated by Django 6.0.5 on 2026-08-25 15:05

from django.db import migrations, models

import core.constants


def prune_draft_inventory_acts(apps, schema_editor):
    InventoryAct = apps.get_model("inventory", "InventoryAct")
    InventoryActPhoto = apps.get_model("inventory", "InventoryActPhoto")
    InventoryActItem = apps.get_model("inventory", "InventoryActItem")

    db_alias = schema_editor.connection.alias
    draft_acts = InventoryAct.objects.using(db_alias).filter(status="draft")
    for act in draft_acts:
        InventoryActPhoto.objects.using(db_alias).filter(act=act).delete()
        InventoryActItem.objects.using(db_alias).filter(act=act).delete()
        act.delete()

    if InventoryAct.objects.using(db_alias).filter(status="draft").exists():
        raise RuntimeError("Migration failed: draft inventory acts still exist.")


TRIGGER_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = 'check_inventory_act_items_count'
    ) THEN
        DROP TRIGGER IF EXISTS trg_check_inventory_act_items_count ON inventory_act_items;
        DROP FUNCTION check_inventory_act_items_count();
    END IF;
END $$;

CREATE OR REPLACE FUNCTION check_inventory_act_items_count()
RETURNS TRIGGER AS $$
DECLARE
    target_act_id INT;
    act_st VARCHAR;
    item_cnt INT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_act_id := OLD.act_id;
    ELSE
        target_act_id := NEW.act_id;
    END IF;

    SELECT status INTO act_st
    FROM inventory_acts
    WHERE id = target_act_id AND deleted_at IS NULL;

    IF act_st = 'finalized' THEN
        SELECT COUNT(*) INTO item_cnt
        FROM inventory_act_items
        WHERE act_id = target_act_id AND deleted_at IS NULL;

        IF item_cnt < 1 THEN
            RAISE EXCEPTION 'Finalized inventory acts must have at least 1 item for act %', target_act_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_inventory_act_items_count ON inventory_act_items;
CREATE CONSTRAINT TRIGGER trg_check_inventory_act_items_count
AFTER INSERT OR UPDATE OR DELETE ON inventory_act_items
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION check_inventory_act_items_count();
"""

DROP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS trg_check_inventory_act_items_count ON inventory_act_items;
DROP FUNCTION IF EXISTS check_inventory_act_items_count();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(prune_draft_inventory_acts, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inventoryact",
            name="status",
            field=models.CharField(
                choices=core.constants.InventoryActStatus.choices,
                default="finalized",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.RunSQL(TRIGGER_SQL, reverse_sql=DROP_TRIGGER_SQL),
    ]
