# Generated by Django 6.0.5 on 2026-06-19 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "type",
                    models.CharField(
                        choices=core.constants.NotificationType.choices,
                        default="general",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Body")),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Related Object Type"),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Related Object ID"),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="Is Read")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Read At")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient"], name="notificatio_recipie_1dd18d_idx"),
                    models.Index(fields=["is_read"], name="notificatio_is_read_3f8c44_idx"),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                ],
            },
        ),
    ]
