# Generated by Django 6.0.5 on 2026-08-09 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=core.constants.NotificationAudience.choices,
                db_index=True,
                default="both",
                max_length=10,
                verbose_name="Audience",
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("push_enabled", models.BooleanField(default=True, verbose_name="Push Enabled")),
                ("payments_enabled", models.BooleanField(default=True, verbose_name="Payments Enabled")),
                ("bookings_enabled", models.BooleanField(default=True, verbose_name="Bookings Enabled")),
                ("maintenance_enabled", models.BooleanField(default=True, verbose_name="Maintenance Enabled")),
                ("leases_enabled", models.BooleanField(default=True, verbose_name="Leases Enabled")),
                ("general_enabled", models.BooleanField(default=True, verbose_name="General Enabled")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("token", models.TextField(unique=True, verbose_name="Token")),
                (
                    "platform",
                    models.CharField(
                        choices=core.constants.DevicePlatform.choices, max_length=10, verbose_name="Platform"
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="Device ID")),
                ("app_version", models.CharField(blank=True, max_length=50, null=True, verbose_name="App Version")),
                ("locale", models.CharField(blank=True, max_length=10, null=True, verbose_name="Locale")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is Active")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="Last Seen At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Token",
                "verbose_name_plural": "Device Tokens",
                "db_table": "notification_device_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_77f2f2_idx"),
                    models.Index(fields=["user", "is_active"], name="notificatio_user_id_93f131_idx"),
                ],
            },
        ),
    ]
