# Generated by Django 6.0.5 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_notificationpreference_messages_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="body_en",
            field=models.TextField(blank=True, null=True, verbose_name="Body"),
        ),
        migrations.AddField(
            model_name="notification",
            name="body_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Body"),
        ),
        migrations.AddField(
            model_name="notification",
            name="body_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Body"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
    ]
