# Generated by Django 6.0.5 on 2026-07-07 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="cost_bearer",
            field=models.CharField(
                blank=True,
                choices=core.constants.CostBearer.choices,
                max_length=20,
                null=True,
                verbose_name="Cost Bearer",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Resolved At"),
        ),
        migrations.CreateModel(
            name="ServiceRequestComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_request_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="maintenance.servicerequest",
                        verbose_name="Service Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request Comment",
                "verbose_name_plural": "Service Request Comments",
                "db_table": "service_request_comments",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["service_request"], name="service_req_service_3f0b79_idx")],
            },
        ),
    ]
