# Generated by Django 6.0.5 on 2026-06-19 06:10

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contract", "0003_publicoffer_owneronboarding"),
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalogItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "service_type",
                    models.CharField(
                        choices=core.constants.VASServiceType.choices,
                        default="other",
                        max_length=20,
                        verbose_name="Service Type",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("partner_name", models.CharField(blank=True, max_length=150, null=True, verbose_name="Partner Name")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Base Price")),
                (
                    "currency",
                    models.CharField(
                        choices=core.constants.Currency.choices, default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Commission Rate"
                    ),
                ),
                (
                    "cashback_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Cashback Rate"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
            ],
            options={
                "verbose_name": "Service Catalog Item",
                "verbose_name_plural": "Service Catalog Items",
                "db_table": "vas_catalog_items",
                "ordering": ["service_type", "name"],
                "indexes": [
                    models.Index(fields=["service_type"], name="vas_catalog_service_c03b12_idx"),
                    models.Index(fields=["is_active"], name="vas_catalog_is_acti_428362_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Deleted At")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Restored At")),
                ("transaction_id", models.UUIDField(blank=True, null=True, verbose_name="Transaction ID")),
                (
                    "status",
                    models.CharField(
                        choices=core.constants.VASOrderStatus.choices,
                        default="requested",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Cost")),
                (
                    "currency",
                    models.CharField(
                        choices=core.constants.Currency.choices, default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "commission_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Commission Earned"
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Cashback Amount"
                    ),
                ),
                ("scheduled_for", models.DateField(blank=True, null=True, verbose_name="Scheduled For")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="vas.servicecatalogitem",
                        verbose_name="Catalog Item",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_orders",
                        to="contract.lease",
                        verbose_name="Lease",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="property.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Order",
                "verbose_name_plural": "Service Orders",
                "db_table": "vas_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant"], name="vas_orders_tenant__387c51_idx"),
                    models.Index(fields=["property"], name="vas_orders_propert_271ed0_idx"),
                    models.Index(fields=["status"], name="vas_orders_status_d7f358_idx"),
                ],
            },
        ),
    ]
