# Generated by Django 6.0.5 on 2026-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Cancellation Reason"),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Completed At"),
        ),
    ]
