# Generated by Django 6.0.5 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vas", "0002_serviceorder_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalogitem",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="name_en",
            field=models.CharField(max_length=150, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="name_ru",
            field=models.CharField(max_length=150, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="servicecatalogitem",
            name="name_uz",
            field=models.CharField(max_length=150, null=True, verbose_name="Name"),
        ),
    ]
